### ISSUE TITLE
Readme removed copyright statement from original project

### ISSUE THREAD

**Issue by puredanger** [viebel/abbinare#1]
The readme omits the copyright statement from the original code:

`Copyright © 2010-2019 David Nolen, Ambrose Bonnaire-Sergeant, Rich Hickey & contributors.`

Please add this back to the README. The original source files should have also contained copyright statements; I've added those in core.match and would appreciate seeing them here as well:

```
;   Copyright (c) Rich Hickey. All rights reserved.
;   The use and distribution terms for this software are covered by the
;   Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
;   which can be found in the file epl-v10.html at the root of this distribution.
;   By using this software in any fashion, you are agreeing to be bound by
;   the terms of this license.
;   You must not remove this notice, or any other, from this software.
```

**Comment by viebel** [comment]
I addressed this issue in https://github.com/viebel/abbinare/commit/e1e4a3c9d083b495a02c080f86a05aa10275e6d0
Let me know if I missed something or close the issue if appropriate.
